name: artista
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.4
  google_sign_in: ^6.1.0
  flutter_login_facebook: ^1.6.2
  flutter_switch: ^0.3.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  google_maps_flutter: ^2.0.0
  intl: ^0.18.0
  fluttertoast: ^8.0.8
  permission_handler: ^10.0.0
  images_picker: ^1.2.11
  url_launcher: ^6.1.10
  connectivity_plus: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/UrbanistMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
